stages:
  - build
  - deploy
  
buildWindowsInstaller:
  stage: build
  image: stereotech/ste-slicer-build-environment:stable
  script: 
    - .\scripts\windows\build.ps1 -SteSlicerPluginsDeployUsername $DEPLOY_USERNAME -SteSlicerPluginsDeployToken $DEPLOY_TOKEN -SteSlicerVersionMajor 0 -SteSlicerVersionMinor 1 -SteSlicerVersionPatch 0
  artifacts:
    name: "steslicer"
    paths:
      - windows-installers
