image: stereotech/ste-slicer-build-environment:stable

stages:
  - build
  - deploy
  
buildWindowsInstaller:
  stage: build
  script: 
    - .\scripts\windows\build.ps1 -CuraVersionMajor 0 -CuraVersionMinor 0 -CuraVersionPatch 1
  artifacts:
    name: "steslicer"
    paths:
      - windows-installers