stages:
  - build
  - deploy

variables:
  GIT_DEPTH: 1

buildInDocker:
  stage: build
  image: stereotech/ste-slicer-build-environment:stable
  tags:
    - windows
    - powershell
    - docker
  before_script:
    - $Env:STESLICER_VERSION_MAJOR=(Get-Date).AddYears(-2019).Year
    - $Env:STESLICER_VERSION_MINOR=(Get-Date).AddYears(-2019).Month
    - $Env:STESLICER_VERSION_PATCH=(Get-Date).AddYears(-2019).Day
    - $Env:STESLICER_VERSION_EXTRA=nightly
    - $Env:STESLICER_BUILD_SRC_PATH=$env:CI_PROJECT_DIR
    - $Env:STESLICER_BUILD_OUTPUT_PATH=$env:CI_PROJECT_DIR\windows-installers
    - $Env:STESLICER_BRANCH_OR_TAG=develop
    - $Env:URANIUM_BRANCH_OR_TAG=steslicer
    - $Env:CURAENGINE_BRANCH_OR_TAG=master
    - $Env:LIBCHARON_BRANCH_OR_TAG=master
    - $Env:STESLICERBINARYDATA_BRANCH_OR_TAG=master
    - $Env:CLIPARSER_BRANCH_OR_TAG=master
    - $Env:CPACK_GENERATOR=NSIS
    - $Env:STESLICER_BUILD_NAME=win64
    - echo $Env:STESLICER_VERSION_MAJOR
    - echo $Env:STESLICER_VERSION_MINOR
    - echo $Env:STESLICER_VERSION_PATCH
    - echo $Env:STESLICER_VERSION_EXTRA
    - echo $Env:STESLICER_BUILD_SRC_PATH
    - echo $Env:STESLICER_BUILD_OUTPUT_PATH
    - echo $Env:STESLICER_BRANCH_OR_TAG
    - echo $Env:URANIUM_BRANCH_OR_TAG
    - echo $Env:CURAENGINE_BRANCH_OR_TAG
    - echo $Env:LIBCHARON_BRANCH_OR_TAG
    - echo $Env:STESLICERBINARYDATA_BRANCH_OR_TAG
    - echo $Env:CLIPARSER_BRANCH_OR_TAG
    - echo $Env:CPACK_GENERATOR
    - echo $Env:STESLICER_BUILD_NAME
  script:
    - powershell.exe -Command cmd /c "$env:CI_PROJECT_DIR\scripts\windows\build_in_docker_vs2015.cmd"
  only:
    - develop
  artifacts:
    name: "steslicer-$env:VERSION_MAJOR.$env:VERSION_MINOR.$env:VERSION_PATCH-nightly"
    paths:
      - windows-installers\build\package

buildNightlyRelease:
  stage: build
  image: stereotech/ste-slicer-build-environment:stable
  tags:
    - windows
    - powershell
    - docker
  before_script:
    - $Env:VERSION_MAJOR=(Get-Date).AddYears(-2019).Year
    - $Env:VERSION_MINOR=(Get-Date).AddYears(-2019).Month
    - $Env:VERSION_PATCH=(Get-Date).AddYears(-2019).Day
  script:
    - .\scripts\windows\build.ps1
      -SteSlicerBranchOrTag "develop"
      -CliParserDeployUsername $CLIPARSER_DEPLOY_USERNAME
      -CliParserDeployToken $CLIPARSER_DEPLOY_TOKEN
      -SteSlicerVersionMajor $env:VERSION_MAJOR
      -SteSlicerVersionMinor $env:VERSION_MINOR
      -SteSlicerVersionPatch $env:VERSION_PATCH
      -SteSlicerVersionExtra "nightly"
  only:
    - develop
  artifacts:
    name: "steslicer-$env:VERSION_MAJOR.$env:VERSION_MINOR.$env:VERSION_PATCH-nightly"
    paths:
      - windows-installers\build\package

deployNightlyRelease:
  stage: deploy
  image: python:latest
  needs: [buildNightlyRelease]
  before_script:
    - pip install awscli
    - VERSION_MAJOR=$(date --date="-19 year" +%-g)
    - VERSION_MINOR=$(date --date="-19 year" +%-m)
    - VERSION_PATCH=$(date --date="-19 year" +%-d)
  script:
    - python -m zipfile -c steslicer-$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH-nightly.zip windows-installers/build/package
    - aws s3 cp steslicer-$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH-nightly.zip s3://software.stereotech.org/steslicer/testing/ --acl public-read
  only:
    - develop

buildStableRelease:
  stage: build
  image: stereotech/ste-slicer-build-environment:stable
  tags:
    - windows
    - powershell
    - docker
  script:
    - .\scripts\windows\build.ps1
      -SteSlicerBranchOrTag "master"
      -CliParserDeployUsername $CLIPARSER_DEPLOY_USERNAME
      -CliParserDeployToken $CLIPARSER_DEPLOY_TOKEN
      -SteSlicerVersionMajor $VERSION_MAJOR
      -SteSlicerVersionMinor $VERSION_MINOR
      -SteSlicerVersionPatch $VERSION_PATCH
      -SteSlicerVersionExtra ""
  only:
    - master
  artifacts:
    name: "steslicer-$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"
    paths:
      - "windows-installers/*.exe"

deployStableRelease:
  stage: deploy
  image: python:latest
  needs: [buildStableRelease]
  before_script:
    - pip install awscli
  script:
    - aws s3 cp "windows-installers" s3://software.stereotech.org/steslicer/stable/ --recursive --include "*.exe" --acl public-read
    - echo $VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH > latest.version
    - aws s3 cp latest.version s3://software.stereotech.org/steslicer/stable/ --acl public-read
  only:
    - master
  when: manual
